# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
trigger:
  branches:
    include:
      - main

variables:
  - group: Mobile

pool:
  vmImage: 'macos-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - task: InstallAppleCertificate@2
    displayName: Install Apple Certificate
    inputs:
      certSecureFile: 'distributionCertificates.p12'
      certPwd: '$(AppleP12Password)'
      keychain: 'temp'
      deleteCert: true
  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Apple Provisioning Profile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'MyInspectionBuddy.mobileprovision'
      removeProfile: true
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSpec: '20.19.0'
  - script: yarn install
    workingDirectory: "AwesomeProject/Frontend-IPA"
    displayName: Install Dependencies
  - script: |
      # Disable autocommit on version bump
      yarn config set version-sign-git-tag false
      yarn config set version-git-tag false
      yarn config set version-commit-hooks false
      # Checkout branch where the build is triggered
      git checkout $(Build.SourceBranchName)
      # Extract existing version of package.json
      oldVer=$(jq -r ".version" package.json)
      # Bump version
      yarn version --patch
      # Add bumped version to staging
      git add *
      # Extract new version of package.json
      newVer=$(jq -r ".version" package.json)
      # Set environment variables
      echo "##vso[task.setvariable variable=OLD_VERSION]$oldVer"
      echo "##vso[task.setvariable variable=NEW_VERSION]$newVer"
    displayName: 'Bump version and set variables'
    workingDirectory: "AwesomeProject/Frontend-IPA"
  # - bash: | 
  #     set -x
  #     npm install -g expo-cli
  #     npm install -g eas-cli
  #   workingDirectory: "AwesomeProject/Frontend-IPA"
  #   displayName: Install EAS build dependencies
  - script: npx expo prebuild -p ios --clean
    workingDirectory: "AwesomeProject/Frontend-IPA"
    displayName: 'Prebuilding the project [generate xcode project]'
  - task: ios-bundle-version@1
    displayName: 'Bump iOS version'
    inputs:
      sourcePath: 'AwesomeProject/Frontend-IPA/ios/AwesomeProject/Info.plist'
      versionCodeOption: 'buildid'
      versionCode: '$(Build.BuildId)'
      versionName: '$(NEW_VERSION)'
      printFile: false
  - script: |
      tag="mobile_$(NEW_VERSION)"
      echo "New tag $tag"
      git add *
      git commit -m "Update version from $(OLD_VERSION) to $(NEW_VERSION)"
      git tag $tag
      git pull --rebase origin $(Build.SourceBranchName)
      git push origin $(Build.SourceBranchName)
      git push --tags
    displayName: Bump commit
  - task: CocoaPods@0
    displayName: 'Install CocoaPods'
    inputs:
      workingDirectory: 'AwesomeProject/Frontend-IPA/ios'
  - bash: |
      CUR_COCOAPODS_VER=`sed -n -e 's/^COCOAPODS: \([0-9.]*\)/\1/p' ios/Podfile.lock`
      ENV_COCOAPODS_VER=`pod --version`
      if [ $CUR_COCOAPODS_VER != $ENV_COCOAPODS_VER ];
      then
        echo "Uninstalling all CocoaPods versions"
        sudo gem uninstall cocoapods --all --executables
        echo "Installing CocoaPods version $CUR_COCOAPODS_VER"
        sudo gem install cocoapods -v $CUR_COCOAPODS_VER
      else 
        echo "CocoaPods version is suitable for the project"
      fi;
      npx pod-install
    workingDirectory: 'AwesomeProject/Frontend-IPA/ios'
    displayName: 'Fix cocoapods'
  - task: Xcode@5
    displayName: 'Build IPA'
    inputs:
      actions: 'clean build'
      configuration: 'Release'
      sdk: 'iphoneos'
      xcWorkspacePath: 'AwesomeProject/Frontend-IPA/ios/AwesomeProject.xcworkspace'
      scheme: 'AwesomeProject'
      packageApp: true
      exportPath: 'output'
      signingOption: manual
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
      provisioningProfileName: '$(APPLE_PROV_PROFILE_NAME)'
      #teamId: '$(TeamID)'
      #exportTeamId: '$(TeamID)'
      #args: '-verbose CODE_SIGNING_ALLOWED=No CODE_SIGNING_REQUIRED=Yes'
  - task: CopyFiles@2
    displayName: 'Copy IPA'
    inputs:
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
      overWrite: true
      flattenFolders: true
  # - task: PublishBuildArtifacts@1
  #   displayName: 'Publish IPA to artifacts'
  #   inputs:
  #     PathtoPublish: '$(build.artifactStagingDirectory)'
  #     ArtifactName: 'ios'
  #     publishLocation: 'Container'
#   - task: AppCenterDistribute@3
#     displayName: 'Upload IPA to AppCenter'
#     inputs:
#       serverEndpoint: 'App Center'
#       appSlug: 'hnadeem/MyProject-iOS'
#       appFile: 'output/MyProject.ipa'
#       releaseNotesOption: 'file'
#       isMandatory: true
#       destinationType: 'groups'
#       distributionGroupId: '058a4704-ea24-4877-a2f0-bdfaff9335dc'
#       isSilent: true