services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:8.14.3
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elk

  logstash:
    container_name: logstash
    image: logstash:8.14.3
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./historical-documents-formatted.json:/tmp/historical-documents-formatted.json
    command: >
      logstash
      -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:8.14.3
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk
    depends_on:
      - elasticsearch

  eland:
    container_name: eland
    image: docker.elastic.co/eland/eland:latest
    command: >
      eland_import_hub_model
      --url http://elasticsearch:9200/
      --hub-model-id sentence-transformers/msmarco-MiniLM-L12-cos-v5
      --task-type text_embedding
      --start
    networks:
      - elk
    depends_on:
      - elasticsearch

  # flask-vs: # for testing
  #   container_name: flask-vs
  #   build: ./
  #   ports:
  #     - '8000:80'

networks:
  elk:
    driver: bridge
